### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#1140]
We already have some examples in `examples/` folder:  
https://github.com/testcontainers/testcontainers-java/tree/master/examples

But some are outdated, and some examples are missing. This is a meta-issue to aggregate all example requests.

Current list:
- [x] ~~https://github.com/testcontainers/testcontainers-java/issues/1136 exposing host port~~ PR submitted: https://github.com/testcontainers/testcontainers-java/pull/1152
- [x] ~~https://github.com/testcontainers/testcontainers-java/issues/1137 modernize Spring boot~~ PR submitted: https://github.com/testcontainers/testcontainers-java/pull/1175
- [ ] ~~https://github.com/testcontainers/testcontainers-java/issues/1138 singleton container~~ PR submitted: https://github.com/testcontainers/testcontainers-java/pull/1178
- [ ] https://github.com/testcontainers/testcontainers-java/issues/1139 cucumber example

We marked them as `good first issue` because we think that contributing examples is a good way to learn Testcontainers and do OSS contributions :)

Comment on the issue you want to work on and it is yours!

**Comment by bsideup** [comment]
@dbyron0 `@DirtiesContext` from Spring? It will re-instantiate a JDBC driver, and Testcontainers will re-create a container.
Although this is not really related to Testcontainers and probably should be done on the test level itself

**Comment by michael-simons** [comment]
I have a nice example how to create a cluster of containers with a shared network, based on the work here (https://github.com/testcontainers/testcontainers-java/pull/1246). I can contribute that as well.

**Comment by kiview** [comment]
@michael-simons Would be great if you add it to the new Gradle examples project :slightly_smiling_face:
